---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS
  region: us-east-1

iamIdentityMappings:
  - arn: arn:aws:iam::757111822982:role/NodeInstanceRole
    groups:
      - system:masters
      - system:bootstrappers
      - system:nodes
    username: system:node:{{EC2PrivateDNSName}}
    noDuplicateARNs: true
  - arn: arn:aws:iam::757111822982:role/EKSClusterRole
    groups:
      - system:masters
      - system:bootstrappers
      - system:nodes
    username: system:node:{{EC2PrivateDNSName}}
    noDuplicateARNs: true
    

  # aws eks update-kubeconfig --name EKS
  # eksctl create iamidentitymapping -f ClusterConfig.yaml
  # eksctl delete iamidentitymapping --cluster EKS --arn arn:aws:iam::757111822982:role/NodeInstanceRole
